### PR TITLE
WIP: Fix different behaviour when accessing maps

### LINKED ISSUE #101: Unexpected behaviour in similar templates
I'm passing ```{"a":null}``` (decoded to map[string]interface{}) to template
```
{{ .a }}
```
and receiving error `there is no field or method "a" in map[string]interface {}`
When I change template to 
```
{{ .["a"] }}
```
and everything works (as expected).
But, if I pass ```{"a":{"b":null}}``` to templates 1)`{{.a.b}}` and 2)`{{.a["b"]}}` I'm receiving error 1)`there is no field or method "b" in map[string]interface {}` and 2) nothing (everything ok).

As I understand, for data structure `map[string]map[string]map[string]map[string]map[string]interface{}` template 
```
{{ .a.b.c.d.e.f }}
```
would raise error, but for
```
{{ .a.b.c.d.e["f"] }}
```
everything works fine.

So my question is:
Why jet can't select the last element in chain of map[string]interface{} by using dots (not square brackets)?

And can I push pr that fix this?

### PR DESCRIPTION
**Pull request by vetcher**
This pr fixes Jet Runtime error when accessing nil element of the `map[string]interface{}` via dot.
Should fix #101

### CODE REVIEW

File: eval_test.go [hunk 1]
```diff
@@ -355,6 +355,8 @@ func TestEvalIndexExpression(t *testing.T) {
 	RunJetTest(t, vars, nil, "IndexExpressionMap_13", `{{nested.nested.nested["nested"]["arr"][0]}}`, "hello")
 	RunJetTest(t, vars, nil, "IndexExpressionMap_14", `{{nested["nested"].nested["nested"].name}}`, "value")
 	RunJetTest(t, vars, nil, "IndexExpressionMap_15", `{{nested["nested"]["nested"].nested.name}}`, "value")
+	RunJetTest(t, vars, nil, "IndexExpressionMap_16_1", `{{nested.nested.nested.nested.nil}}`, "<nil>")
```
Comment (annismckenzie) [inline eval_test.go]: @c2h5oh: wouldn't we also want this to be an empty string instead of the `<nil>` (same as for structs, see #97 and #100)?

**Comment by annismckenzie** [comment]
Awesome, thanks! Merging.

File: eval_test.go (hunk 1 above)
Comment (c2h5oh) [reply eval_test.go]: Yeah, it's better to be consistent

**Comment by annismckenzie** [comment]
It would be awesome if you were to take a stab at that. 😅
