### PR TITLE
cache more aggressively; remove Set.LoadTemplate()

### LINKED ISSUE #180: Performance: Steep decline between v2 and v5
I've been doing several proof of concepts and the performance of v5's loading of templates is significantly less than of the v2 branch:
```
BenchmarkJets
BenchmarkJets/Jetv2
BenchmarkJets/Jetv2-8         	   48260	     24372 ns/op	    5040 B/op	      87 allocs/op
BenchmarkJets/Jetv5
BenchmarkJets/Jetv5-8         	    3828	    267862 ns/op	   36687 B/op	     456 allocs/op
```

## The setup
[Versions](https://github.com/CloudyKit/jet/releases):
- github.com/CloudyKit/jet v2.1.2+incompatible
- github.com/CloudyKit/jet/v5 v5.1.1

The implementation and templates are identical, with the exception of some differences required for the different Jet versions:
```sh
$ find . -type f -name "*.jet" -print -exec diff -Naruw ../jetv2/{} ../jetv5/{} \;
```
```diff
./views/leaderboard.jet
--- ../jetv2/./views/leaderboard.jet	2020-10-20 10:18:04.000000000 +0200
+++ ../jetv5/./views/leaderboard.jet	2020-10-20 12:55:05.000000000 +0200
@@ -1,8 +1,8 @@
-{{import "partials/leaderboard_row.jet"}}
+{{import "/partials/leaderboard_row.jet"}}

 <table>
     <!-- Control flow is a must. This includes iterating over arrays, if/elseif/else statements and ternaries. -->
-    {{range competitor := .Leaderboard}}
+    {{range _, competitor := .Leaderboard}}
     <!-- comments do not appear in the rendered HTML -->
         {* `$competitor` is of type `User` *}
         {{yield leaderboard_row(user=competitor)}}
./views/index.jet
--- ../jetv2/./views/index.jet	2020-10-20 10:18:04.000000000 +0200
+++ ../jetv5/./views/index.jet	2020-10-20 12:45:10.000000000 +0200
@@ -1,6 +1,6 @@
-{{extends "layouts/main.jet"}}
+{{extends "/layouts/main.jet"}}

-{{import "partials/ui.jet"}}
+{{import "/partials/ui.jet"}}

 {{block body()}}
     <script type="text/javascript">
./views/layouts/main.jet
./views/layouts/header.jet
--- ../jetv2/./views/layouts/header.jet	2020-10-26 09:09:56.000000000 +0100
+++ ../jetv5/./views/layouts/header.jet	2020-10-20 12:45:03.000000000 +0200
@@ -1,4 +1,4 @@
-{{import "partials/ui.jet"}}
+{{import "/partials/ui.jet"}}

 <div id="header">
     <div id="menu">
./views/layouts/footer.jet
./views/partials/ui.jet
./views/partials/leaderboard_row.jet
```
The files:
```
.
├── jet.go
└── views
    ├── index.jet
    ├── layouts
    │   ├── footer.jet
    │   ├── header.jet
    │   └── main.jet
    ├── leaderboard.jet
    └── partials
        ├── leaderboard_row.jet
        └── ui.jet
```

## The benchmark
```go
import (
	jetversion2 "github.com/CloudyKit/jet"
	jetversion5 "github.com/CloudyKit/jet/v5"
	// ..
)

func BenchmarkJets(b *testing.B) {
	if wd, err := os.Getwd(); err == nil && filepath.Base(wd) == "template" {
		_ = os.Chdir("..")
	}

	tr := reflect.ValueOf(template.TranslateFunc("en"))
	data := template.ExampleContext()

	b.Run("Jetv2", func(b *testing.B) {

		views := jetversion2.NewHTMLSet("./template/jetv2/views")
		views.SetDevelopmentMode(false)

		for i := 0; i < b.N; i++ {
			t, err := views.GetTemplate("index.jet")
			if err != nil {
				b.Errorf("Error in benchmark %s", err)
			}

			err = t.Execute(ioutil.Discard, jetversion2.VarMap{"T": tr}, data)
			if err != nil {
				b.Errorf("Error in benchmark %s", err)
			}
		}
	})

	b.Run("Jetv5", func(b *testing.B) {

		views := jetversion5.NewHTMLSet("./template/jetv5/views")
		views.SetDevelopmentMode(false)
		views.SetExtensions([]string{""}) // v5 specific optimisation

		for i := 0; i < b.N; i++ {
			t, err := views.GetTemplate("index.jet")
			if err != nil {
				b.Errorf("Error in benchmark %s", err)
			}

			err = t.Execute(ioutil.Discard, jetversion5.VarMap{"T": tr}, data)
			if err != nil {
				b.Errorf("Error in benchmark %s", err)
			}
		}
	})
}
```

## Considerations 
I noticed quite a bit of time spent in io (`Loader.Exists`). I wrote a quick-n-dirty Loader that pre-fetches all *.jet files and adds them to a map for faster subsequent lookups. This reduces the execution time to 17 ms (down from 267ms). But I think it only masks the problem, instead of properly solving it.

I noticed many invocations to `Loader.Exists` and `Loader.Load()` for already observed files. My *guess* so far is that some state should be preserved in `func (st *Runtime) executeList` when `st.executeInclude()` is invoked. Or that the way file paths are canonicalised should be more in line with how templates can be used in version 5. e.g.:
- `{{ include "./index.jet" }}`
- `{{ include "/index.jet" }}`
- `{{ include "index.jet" }}`

might all point to the same file.

Screenshot 2020-10-26 at 16 38 55
Screenshot 2020-10-26 at 16 40 21

## Further findings
After I've plugged a different Loader I managed to get it down to the following. However I think this isn't the approach to take. I think the lazy-loading approach is probably a fine route to take, but right now it appears to not resolving efficiently.
```
BenchmarkJets
BenchmarkJets/Jetv2
BenchmarkJets/Jetv2-8         	   49384	     23685 ns/op	    5041 B/op	      87 allocs/op
BenchmarkJets/Jetv5
BenchmarkJets/Jetv5-8         	   69686	     17440 ns/op	    5091 B/op	      72 allocs/op
```

### PR DESCRIPTION
**Pull request by sauerbraten**
~~Keeping track of wether or not to cache templates that are imported/extended during Parse() is too much work, so Parse() is gone for now.~~ LoadTemplate() is removed in favor of a new in-memory Loader where you can add templates on-the-fly (which is also used for tests without template files). Using it together with a file loader via a multi loader restores the previous functionality.

I believe this fixes #180.

### CODE REVIEW

File: loader.go [hunk 1]
```diff
@@ -39,22 +42,56 @@ var _ Loader = (*OSFileSystemLoader)(nil)
...
+type InMemLoader struct {
+	files map[string][]byte
+}
+
+// compile time check that we implement Loader
+var _ Loader = (*InMemLoader)(nil)
+
+func NewInMemLoader() *InMemLoader {
+	return &InMemLoader{
+		files: map[string][]byte{},
```
Comment (Dynom) [inline loader.go:74]: Accessing `l.files` without mutex allows for race conditions. There a few areas within Jet that could use a second look (see also: https://github.com/CloudyKit/jet/issues/181)

File: template.go [hunk 2]
```diff
@@ -174,24 +147,33 @@ func (s *Set) getTemplate(templatePath string) (t *Template, err error) {
 		}
 	}
 
-	return s.getTemplateFromLoader(templatePath)
+	t, err = s.getTemplateFromLoader(templatePath)
+	if err == nil && !s.developmentMode {
+		s.templates[templatePath] = t
```
Comment (Dynom) [inline template.go:152]: Access to `s.templates` should either be guarded with a mutex or use the type [`sync.Map`](https://golang.org/pkg/sync/#Map), as I suspect this type is likely to be a high read on single write.

**Comment by sauerbraten** [comment]
Thanks for your comments, @Dynom! I'd like to address Jet's concurrency-safety later in a new PR targeting #181, and ignore these for now, okay?

File: loader.go (hunk 1 above)
Comment (sauerbraten) [reply loader.go:75]: will be addressed in fix for #181

File: template.go (hunk 2 above)
Comment (sauerbraten) [reply template.go:153]: will be addressed in fix for #181

**Comment by sauerbraten** [comment]
I re-added the Set.Parse() method and cleaned up the commit history.
